### ISSUE TITLE
leverage add_user_data_ref / add_user_code_ref

### ISSUE THREAD

**Issue by psifertex** [lse/wakare#1]
There's some newer APIs available on the Binary Ninja dev channel you might not be aware of called `add_user_data_ref` and `add_user_code_ref` that this plugin would probably benefit from. If you create those custom references you'll get all the usual xref behavior in BN in addition to the custom UI which you've implemented (which is still beneficial because of the hit count).

**Comment by SiD3W4y** [comment]
Feature was added on direct cross reference queries (for performance reasons).
