### ISSUE TITLE
move binary ninja plugin to a submodule

### ISSUE THREAD

**Issue by psifertex** [lse/wakare#2]
Unfortunately right now Binary Ninja plugins can't exist as subfolders in an existing project, but if you moved the plugin contents into a submodule I'd be happy to submit a PR to make the `plugin.json` match the new repo format which lets users then install it via the UI.

**Comment by SiD3W4y** [comment]
I moved everything to https://github.com/SiD3W4y/wakare-ui

**Comment by psifertex** [comment]
Got it, thanks! Issued the PR.
